services:
  postrgres:
    container_name: crud_java
    image: postgres
    ports:
     - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=crud_java
